### ISSUE TITLE
Output - undefined

### ISSUE THREAD

**Issue by markaves** [scotch-io/node-web-scraper#7]
When i ran the script, i get an output.json that has an entry of "undefined".  Maybe IMDB got changed?

**Comment by markaves** [comment]
I added a logging for error and it looks like it is redirecting to https and it cannot handle the certificate

error: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
File successfully written! - Check your project directory for the output.json file

**Comment by markaves** [comment]
Fixed:  I have updated to code to look like this
request({
     url : url,
     rejectUnauthorized : false
	}, 
	function(error, response, html){
